services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/neurolearn

  client:
    image: node:18-alpine # Use a standard Node.js image
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
